/**
 * Windows daemon: **supervisor script + scheduled task**.
 *
 * Why not "task + `RestartOnFailure`": measured on two tasks (78s / 165s, two observations) the settings did take effect
 * (`RestartInterval=PT1M`, `RestartCount=3`), but after a non-zero exit the script **ran only once** — the task never
 * restarted it. Task Scheduler only restarts when "the action failed to start". So if the agent crashes, nobody
 * respawns it, whereas launchd / systemd do this via their own process supervision. Self-healing therefore has to live in the script:
 * the task runs a `while ($true) { node … start; Start-Sleep }` supervisor loop.
 *
 * Two more claims disproved in practice (don't try them again):
 * - `New-ScheduledTaskTrigger -AtLogOn -RepetitionInterval` is a **parameter-set conflict**; the task cannot even be created.
 * - `LastTaskResult=267009` is `SCHED_S_TASK_RUNNING` (currently running), not an error code.
 *
 * This file is **pure functions** (script body / PowerShell statements / parsing). The two entries that actually run commands
 * (`stopWindowsDaemon` / `startWindowsDaemon`) take `run` as an inject point — unit tests never talk to Task Scheduler for real.
 */
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

export const WINDOWS_DAEMON_TASK = 'Lifeline Agent';

/**
 * Filename of the supervisor script. Used in two places, so it is a constant:
 *  - write it to disk (`windowsDaemonScriptPath()`)
 *  - **recognize the supervisor process** in `stop` (powershell whose command line contains this name — wait until it leaves the process table)
 */
export const WINDOWS_DAEMON_SCRIPT_NAME = 'daemon.ps1';

/** PowerShell single-quoted literal: single quotes inside the value must be doubled, or the statement is a syntax error. */
function esc(value: string): string {
  return value.replace(/'/g, '\'\'');
}

/**
 * PowerShell invocation shape for the scheduled task (`-NoProfile` so the user's profile cannot interfere;
 * pass a single statement, not script contents).
 */
export function windowsTaskInvocation(statement: string): { cmd: string; args: string[] } {
  return {
    cmd: 'powershell.exe',
    args: ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', statement],
  };
}

/** **Body** of the supervisor-loop script (no BOM; writing to disk is `writeWindowsDaemonScript`). */
export function windowsDaemonScript(nodePath: string, mjsPath: string): string {
  // Keep the body ASCII on purpose: `powershell.exe -File` on 5.1 reads **BOM-less** files as the system ANSI code page,
  // so Chinese comments get swallowed / fail to parse. Comments stay English; non-ASCII **data** (Chinese username paths) is covered by the BOM.
  return [
    '# generated by `lifeline daemon install` -- do not edit; reinstall instead',
    `$node = '${esc(nodePath)}'`,
    `$mjs = '${esc(mjsPath)}'`,
    `$logDir = Join-Path $PSScriptRoot 'logs'`,
    // Create the directory with .NET, not `New-Item`: **`New-Item` has no `-LiteralPath` parameter at all**
    // (measured on a real machine: `A parameter cannot be found that matches parameter name 'LiteralPath'`),
    // and `-Path` treats `[]` as wildcards. `CreateDirectory` has no glob semantics, is idempotent, and creates parents.
    `[System.IO.Directory]::CreateDirectory($logDir) | Out-Null`,
    `$out = Join-Path $logDir 'agent.out.log'`,
    `$err = Join-Path $logDir 'agent.err.log'`,
    // Where launch-layer failures go. Deliberately **not** out/err: those files are exactly the ones "held by another agent"
    // (see the diagnostic block below), so writing them would fail too.
    `$sup = Join-Path $logDir 'supervisor.log'`,
    '',
    '# Restart backoff. A misconfigured agent (rejected token / unreachable server)',
    '# exits in about a second, and a fixed sleep would turn that into an unlimited',
    '# restart loop that also floods the logs. Doubling to a 60s cap, reset after a',
    '# healthy run. (launchd/systemd have no real backoff either; we add one here.)',
    '#',
    '# NOTE: the first fast exit sleeps 10s, not 5 -- $backoff is doubled *before* the',
    '# sleep, and 5 only comes back once a run has stayed up for a full minute.',
    '#',
    '# NOTE: these logs are append-only and never rotated. A restart storm is exactly',
    '# what the backoff above exists to prevent, but a long-lived install should still',
    '# be checked for size by whatever monitors the machine.',
    '$backoff = 5',
    'while ($true) {',
    '# Wall clock is not safe here: an NTP/DST step backwards makes $ran negative, and a',
    '# forward step can make a fast exit look like a healthy run. Stopwatch is monotonic.',
    '  $sw = [System.Diagnostics.Stopwatch]::StartNew()',
    '  # Redirection goes through cmd.exe on purpose: PowerShell 5.1 writes `>>` as',
    '  # UTF-16LE with a BOM (measured: FF FE 68 00 65 00), which no log tooling on',
    '  # this project can read and which disagrees with the launchd/systemd logs.',
    '  # cmd.exe appends raw bytes, and 1>/2> keep stdout and stderr apart.',
    // `" is PowerShell's escaped quote (not a backslash!) so the path is handed to cmd.exe as-is.
    '  & cmd.exe /c "`"$node`" `"$mjs`" start 1>> `"$out`" 2>> `"$err`""',
    '  $sw.Stop()',
    '  # A launch that dies in milliseconds never ran the agent: cmd could not even open the',
    '  # redirect targets (measured, 2026-09-20: "The process cannot access the file because it',
    '  # is being used by another process" -- a leftover lifeline agent still holds the logs).',
    '  # That message bubbles up to this script, whose stdout/stderr the Task Scheduler',
    '  # discards. Record it in a file the other agent has no handle on.',
    '  if ($LASTEXITCODE -ne 0 -and $sw.Elapsed.TotalSeconds -lt 5) {',
    '    & cmd.exe /c "echo [%DATE% %TIME%] launch failed, exit $LASTEXITCODE -- another lifeline agent may still hold the logs; run: lifeline stop 1>> `"$sup`""',
    '  }',
    '  if ($sw.Elapsed.TotalSeconds -ge 60) {',
    '    $backoff = 5',
    '  } else {',
    '    $backoff = [Math]::Min(60, $backoff * 2)',
    '  }',
    '  Start-Sleep -Seconds $backoff',
    '}',
    '',
  ].join('\n');
}

/**
 * Write the supervisor script to disk.
 *
 * **Must be UTF-8 with BOM**: the script embeds **data** like `<home>\runtime\node.exe`, and a Chinese Windows
 * user directory is often `C:\Users\ZhangSan\` — ASCII cannot hold a non-ASCII path. 5.1's `-File` only reads
 * UTF-8 when it sees a BOM; without one it uses ANSI/GBK, the path garbles, and the agent never starts.
 */
export function writeWindowsDaemonScript(filePath: string, nodePath: string, mjsPath: string): void {
  writeFileSync(filePath, `\uFEFF${windowsDaemonScript(nodePath, mjsPath)}`, 'utf-8');
}

export function windowsTaskAction(scriptPath: string): { execute: string; argument: string } {
  return {
    execute: 'powershell.exe',
    // `-WindowStyle Hidden` is deliberate: using node.exe as the action flashes a console window; hiding via VBS
    // makes the task "finish instantly" and kills self-healing. Wrapping in a hidden-window powershell gets both —
    // no flash, and the task stays Running while node is alive.
    argument: `-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "${scriptPath}"`,
  };
}

export function windowsRegisterPsCommand(opts: { scriptPath: string; taskName?: string }): string {
  const name = opts.taskName ?? WINDOWS_DAEMON_TASK;
  const action = windowsTaskAction(opts.scriptPath);
  return [
    `$a = New-ScheduledTaskAction -Execute '${esc(action.execute)}' -Argument '${esc(action.argument)}'`,
    `$t = New-ScheduledTaskTrigger -AtLogOn`,
    // `-UserId` **is required**: omitting it makes the whole statement fail with
    // `Cannot process command because of one or more missing mandatory parameters: UserId.`
    // → the task never gets registered. Take `DOMAIN\user` from WindowsIdentity (`$env:USERNAME` does not resolve under a domain account).
    //
    // Interactive + Limited is **least privilege**: registering from an "Run as administrator" shell would leave the whole agent
    // running as admin. This is not "fixing UIPI" — UIPI blocks low-integrity → high-integrity; high-to-medium messages are already allowed.
    `$p = New-ScheduledTaskPrincipal -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) -LogonType Interactive -RunLevel Limited`,
    // ExecutionTimeLimit defaults to **72 hours**: without an explicit zero, the scheduler kills the agent after three days
    // with no error. `-Seconds 0` falls back to the default on some versions, so the next statement read-backs to verify.
    `$s = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Seconds 0) -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries`,
    `Register-ScheduledTask -TaskName '${esc(name)}' -Action $a -Trigger $t -Principal $p -Settings $s -Force | Out-Null`,
    // `-AtLogOn` only fires on the next login; the end of `setup` relies on this line to bring the daemon up **immediately**.
    `Start-ScheduledTask -TaskName '${esc(name)}'`,
  ].join('; ');
}

/**
 * PowerShell statement that stops the daemon. **Does not unregister the task** — that is `uninstall`'s job.
 *
 * Stopping the task does not guarantee collecting the whole process tree it spawned (measured only in the "supervisor has no children" case),
 * so this adds an orphan sweep. The criterion is **the parent is already gone from the process table**, not command-line matching:
 * a user-run foreground `node runtime\lifeline.mjs start` has the same command line as the daemon-spawned one,
 * so a blanket kill would take the user's foreground agent with it (`stop` means "stop the daemon only").
 */
export function windowsStopPsCommand(
  taskName: string = WINDOWS_DAEMON_TASK,
  /**
   * Full path of the supervisor script. **The criterion must bind to this task's script**, not just the filename: if another
   * powershell is running `-File …\daemon.ps1` (another probe, a session editing the script), matching basename only
   * makes this `stop` wait the full 10s for nothing. When omitted, fall back to the basename (still better than not waiting).
   */
  scriptPath: string = WINDOWS_DAEMON_SCRIPT_NAME,
): string {
  return [
    `Stop-ScheduledTask -TaskName '${esc(taskName)}' -ErrorAction SilentlyContinue`,
    // ① Wait until the **supervisor process is actually gone from the process table**.
    //
    // `Stop-ScheduledTask` is **async**: by the time it returns, that powershell is often still in the table, so cmd/node
    // still "have a live parent" and are judged "not orphans". Measured on a real machine (2026-09-20, full CLI path): after `stop` one
    // node remained; **a second `stop` was needed to collect it**.
    //
    // ⚠️ The fix **must not be a fixed sleep** — that only shrinks the race to a guessed number of milliseconds (first attempt was 800ms;
    // on a slow machine / stuck Task Scheduler it is still not enough, i.e. the same bug with a different number). Wait for an **observable condition**:
    // powershell whose command line contains `daemon.ps1` leaves the table; after a 10s timeout proceed even if the supervisor is still there (prefer continuing the sweep
    // over stalling the user here).
    `$waited = 0`,
    `while ($waited -lt 20) {`,
    // ⚠️ `-ne $PID` is required: **this statement's own command line already contains `daemon.ps1`** (in the `-like`
    // literal below), and it is run as `powershell.exe -Command <this statement>` — so it can
    // **permanently match itself** and never wait down to 0 (measured: waited the full 10s, `stop` went from ~3s to ~20s).
    `  $sup = @(Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" -ErrorAction SilentlyContinue | Where-Object { $_.ProcessId -ne $PID -and $_.CommandLine -and $_.CommandLine -like '*${scriptPath}*' })`,
    `  if ($sup.Count -eq 0) { break }`,
    `  Start-Sleep -Milliseconds 500`,
    `  $waited = $waited + 1`,
    `}`,
    // Supervisor still alive after timeout (stuck Task Scheduler): **must kill it explicitly**. The supervisor is not in the
    // node/cmd candidate set below, so the orphan sweep never touches it; while it lives, cmd/node all "have a live parent" → the orphan sweep
    // idles two rounds and quits. So "continue sweeping after timeout" that lives only in a comment, without this step, is actually **giving up**.
    `if ($waited -ge 20) {`,
    `  $sup | ForEach-Object { Stop-Process -Id $_.ProcessId -ErrorAction SilentlyContinue }`,
    `  Start-Sleep -Milliseconds 800`,
    `  $sup | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }`,
    `}`,
    // ② Sweep orphans only after the supervisor is gone. The tree is `powershell(-File daemon.ps1) → cmd.exe(the redirect layer) →
    // node.exe(agent)`, and **both cmd.exe and node.exe command lines contain `lifeline.mjs`**. Consequence of a single pass:
    // cmd's parent (powershell) is dead → cmd is collected; but node's parent (cmd.exe) is **still alive in the same snapshot** →
    // node escapes this round. So iterate to a fixed point.
    `$round = 0`,
    `$empty = 0`,
    `while ($round -lt 5) {`,
    `  $round = $round + 1`,
    // `$live` must be the **full** PID set (the criterion is "is the parent still around") — take it from `Get-Process` (much faster than CIM,
    // and CIM's full-table CommandLine takes seconds on a machine with thousands of processes). Then narrow candidates by name to node/cmd.
    // ⚠️ Do not narrow `$live` to "candidates only": a user's foreground `lifeline start` may have parent
    // `WindowsTerminal.exe`, which would then be misjudged as an orphan and killed.
    `  $live = @{}`,
    `  foreach ($p in @(Get-Process -ErrorAction SilentlyContinue)) { $live[[int]$p.Id] = $true }`,
    `  $cand = @(Get-CimInstance Win32_Process -Filter "Name='node.exe' OR Name='cmd.exe'" -ErrorAction SilentlyContinue)`,
    `  $orphans = @($cand | Where-Object { $_.CommandLine -and $_.CommandLine -like '*${AGENT_ENTRY_BASENAME}*' -and (-not $live.ContainsKey([int]$_.ParentProcessId)) })`,
    // Two consecutive empty rounds count as clean. The supervisor is **already** gone, so empty here is "truly clean"; keep one extra round because
    // after collecting cmd, node only becomes an orphan on the next round — judging one empty round would quit too early.
    `  if ($orphans.Count -eq 0) { $empty = $empty + 1; if ($empty -ge 2) { break } ; Start-Sleep -Milliseconds 600; continue }`,
    `  $empty = 0`,
    // Give them a chance to exit themselves (teardown, upload) before a force kill.
    `  $orphans | ForEach-Object { Stop-Process -Id $_.ProcessId -ErrorAction SilentlyContinue }`,
    `  Start-Sleep -Seconds 2`,
    `  $orphans | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }`,
    `}`,
  ].join('; ');
}

export function windowsUnregisterPsCommand(
  taskName: string = WINDOWS_DAEMON_TASK,
  scriptPath: string = WINDOWS_DAEMON_SCRIPT_NAME,
): string {
  return [
    windowsStopPsCommand(taskName, scriptPath),
    `Unregister-ScheduledTask -TaskName '${esc(taskName)}' -Confirm:$false -ErrorAction SilentlyContinue`,
  ].join('; ');
}

/**
 * Filename that always appears in the runtime agent process's command line.
 *
 * Extracted as a constant because it **appears in two criteria** (a pure function in this file, and the generated inline PowerShell),
 * and "the two must match" used to be maintained by a comment alone — changing the runtime filename on only one side is a miss-kill or a false-kill.
 */
export const AGENT_ENTRY_BASENAME = 'lifeline.mjs';

export function windowsStatusPsCommand(taskName: string = WINDOWS_DAEMON_TASK): string {
  return [
    `$t = Get-ScheduledTask -TaskName '${esc(taskName)}' -ErrorAction SilentlyContinue`,
    `if ($t) { 'State=' + $t.State }`,
    `$i = Get-ScheduledTaskInfo -TaskName '${esc(taskName)}' -ErrorAction SilentlyContinue`,
    `if ($i) { 'LastTaskResult=' + $i.LastTaskResult }`,
    // Read-back check: the default 72 hours would make the agent vanish silently after three days.
    `if ($t) { 'ExecutionTimeLimit=' + $t.Settings.ExecutionTimeLimit }`,
  ].join('; ');
}

/**
 * List pids of every lifeline agent in the process table (**no wait**) — the "before start" snapshot for the read-back check.
 *
 * ⚠️ The criterion "node.exe + command line contains `lifeline.mjs`" also hits **the caller itself**: `lifeline daemon
 * install`'s command line is `node.exe …lifeline.mjs daemon install`. So the caller must
 * exclude the CLI with `excludePid`, then take a set difference against the "after start" snapshot (`newLifelinePids`) —
 * checking only "did anything match" is always true (a defect found in code review on a real machine).
 */
export function windowsLifelinePidsPsCommand(excludePid?: number): string {
  const notSelf = excludePid ? ` -and $_.ProcessId -ne ${excludePid}` : '';
  return [
    `$p = @(Get-CimInstance Win32_Process -Filter "Name='node.exe'" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -and $_.CommandLine -like '*${AGENT_ENTRY_BASENAME}*'${notSelf} })`,
    `'agent=' + (($p | ForEach-Object { $_.ProcessId }) -join ',')`,
  ].join('; ');
}

/**
 * The "after start" snapshot: wait a few seconds first (fork → process-table visibility is not instant; 3s is enough) then list pids.
 *
 * Task `Running` only means the **supervisor** is alive — the agent itself may fail at the launch layer every round
 * (`1>>` cannot open `agent.out.log` while another lifeline agent holds it, so node is never spawned;
 * see supervisor.log in `windowsDaemonScript`).
 */
export function windowsAgentProbePsCommand(opts: { excludePid?: number; waitSeconds?: number } = {}): string {
  const wait = opts.waitSeconds ?? 3;
  return `Start-Sleep -Seconds ${wait}; ${windowsLifelinePidsPsCommand(opts.excludePid)}`;
}

/** Parse `agent=<pid,pid>`; empty output / a failed statement always return [] (conservative: do not count as "came up"). */
export function parseWindowsAgentPids(stdout: string): number[] {
  const m = /agent=([0-9,]*)/.exec(stdout);
  if (!m)
    return [];
  return m[1]!
    .split(',')
    .map(s => Number(s))
    .filter(n => Number.isInteger(n) && n > 0);
}

/** Pids that appeared after start = agents this run actually spawned (CLI itself / leftovers / foreground are already in `before`). */
export function newLifelinePids(before: readonly number[], after: readonly number[]): number[] {
  const known = new Set(before);
  return after.filter(pid => !known.has(pid));
}

export interface WindowsTaskStatus {
  state?: string;
  lastTaskResult?: number;
  executionTimeLimit?: string;
  running: boolean;
}

/** `0x41301` = `SCHED_S_TASK_RUNNING`: the task is running, **not** an error code. */
const SCHED_S_TASK_RUNNING = 267009;

/**
 * Whether `ExecutionTimeLimit` is "unlimited".
 *
 * The read-back form is **not fixed**: measured locally as ISO 8601 duration **`PT0S`**, while the schedule writes `00:00:00`
 * (TimeSpan's default `ToString()`). Both must be recognized, or a zero duration is misread as "has a limit" and we false-alarm every day.
 * The truly dangerous value is the default `PT72H` (agent vanishes silently after three days).
 */
export function isUnlimitedExecution(value: string | undefined): boolean {
  if (!value)
    return false;
  const v = value.trim();
  // ISO 8601 duration (`PT0S` / `PT0H` / `PT0M` / `P0D` / `PT0H0M0S`) or TimeSpan
  // G / c format (`00:00:00` / `00:00:00.0000000` / **`0.00:00:00`** — zero with a day field,
  // a counter-example from review; missing it would treat "zero duration" as having a limit) — always judge by "does the duration contain a non-zero digit",
  // which is more robust than a whitelist. Missing a whitelist entry is only a **false alarm** (the note says the scheduler will kill the agent, but we actually wrote
  // `-Seconds 0`), but since we can get it right in one go, don't leave this tail.

  if (/^P/i.test(v) || /^(\d+\.)?\d{1,2}:\d{2}:\d{2}(\.\d+)?$/.test(v)) {
    return !/[1-9]/.test(v);
  }
  return v === '0';
}

export function parseWindowsTaskStatus(stdout: string): WindowsTaskStatus {
  const status: WindowsTaskStatus = { running: false };
  for (const line of stdout.split(/\r?\n/)) {
    const m = /^([A-Z]+)\s*=\s*(.*)$/i.exec(line.trim());
    if (!m)
      continue;
    const [, key, value] = m;
    if (key === 'State')
      status.state = value;
    else if (key === 'LastTaskResult')
      status.lastTaskResult = Number(value);
    else if (key === 'ExecutionTimeLimit')
      status.executionTimeLimit = value;
  }
  status.running = status.state === 'Running' || status.lastTaskResult === SCHED_S_TASK_RUNNING;
  return status;
}

export interface ProcRow {
  pid: number;
  ppid: number;
  commandLine?: string;
}

/**
 * Pick lifeline agent processes whose **parent is no longer in the process table**.
 *
 * Must stay **identical** to the PowerShell criterion in `windowsStopPsCommand()` (that side is the inline equivalent):
 * matching command line alone would collect a user's foreground agent too.
 */
export function pickOrphanLifelinePids(snapshot: readonly ProcRow[]): number[] {
  // ⚠️ The production path is the equivalent inline PowerShell in `windowsStopPsCommand()`, **not this function** —
  // this is the spec-extracted, unit-testable "criterion expression"; the two must be word-for-word synonymous (change one, change the other).
  // Kept so the criterion can be asserted; the `AGENT_ENTRY_BASENAME` constant binds both sides.
  const alive = new Set(snapshot.map(p => p.pid));
  return snapshot
    // Lowercase compare to match the PowerShell side: `-like` there is **case-insensitive**,
    // while JS `includes` is sensitive — without unifying, a command line like `LIFELINE.MJS` would match on only one side.
    .filter(p => p.commandLine?.toLowerCase().includes(AGENT_ENTRY_BASENAME) === true)
    .filter(p => !alive.has(p.ppid))
    .map(p => p.pid);
}

export interface WindowsDaemonDeps {
  run?: typeof spawnSync;
  log?: (msg: string) => void;
  /** Full path of the supervisor script (the criterion must bind to this task's script; see `windowsStopPsCommand`'s param docs). */
  scriptPath?: string;
}

/** Stop the daemon. Silently return when the task does not exist (clean install) — that is not an error. */
export function stopWindowsDaemon(deps: WindowsDaemonDeps = {}): boolean {
  return runWindowsStatement(windowsStopPsCommand(WINDOWS_DAEMON_TASK, deps.scriptPath), deps);
}

/** Start the daemon. If the task does not exist, `daemon install` has never been run; leave the wording to the caller. */
export function startWindowsDaemon(deps: WindowsDaemonDeps = {}): boolean {
  return runWindowsStatement(`Start-ScheduledTask -TaskName '${esc(WINDOWS_DAEMON_TASK)}'`, deps);
}

/**
 * Run one PowerShell statement (really calls `powershell.exe`; `run` is the inject point).
 *
 * Returning `false` only means "this statement did not succeed" — the caller decides whether to degrade or hint; do not treat it as fatal:
 * on a clean machine `Stop-ScheduledTask` also returns non-zero when the task is missing.
 */
export function runWindowsStatement(statement: string, deps: WindowsDaemonDeps = {}): boolean {
  const run = deps.run ?? spawnSync;
  const invocation = windowsTaskInvocation(statement);
  try {
    // 60s: `stop` waits for the supervisor to disappear (≤10s) + iterative orphan sweep (up to ~13s); a 30s budget is too tight.
    const r = run(invocation.cmd, invocation.args, { stdio: 'ignore', timeout: 60_000, windowsHide: true });
    return r.status === 0;
  }
  catch {
    return false;
  }
}

/** Run one PowerShell statement and return stdout (for status queries). */
export function queryWindowsStatement(statement: string, deps: WindowsDaemonDeps = {}): string {
  const run = deps.run ?? spawnSync;
  const invocation = windowsTaskInvocation(statement);
  try {
    const r = run(invocation.cmd, invocation.args, { encoding: 'utf8', timeout: 30_000, windowsHide: true });
    return r.stdout ?? '';
  }
  catch {
    return '';
  }
}
